volumes:
  pg_data:
  static:
  media:


services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    depends_on:
      - db
    image: zaphire12/foodgram-backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media

  frontend:
    env_file: .env
    image: zaphire12/foodgram_frontend
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static

  gateway:
    depends_on:
      - backend
      - frontend
    image: zaphire12/foodgram_gateway
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - static:/static/
      - media:/media